kind: Secret
apiVersion: v1
metadata:
    name: game-library-dbconfig
    namespace: game-library
data:
    DB_DSN: {{echo db_dsn | base64}}
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
    name: game-library-igdb
    namespace: game-library
data:
    IGDB_CLIENT_ID: {{echo igdb_client_id | base64}}
    IGDB_CLIENT_SECRET: {{echo igdb_client_secret | base64}}
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
    name: game-library-uploadcare
    namespace: game-library
data:
    UPLOADCARE_PUBLIC_KEY: {{echo uploadcare_public_key | base64}}
    UPLOADCARE_SECRET_KEY: {{echo uploadcare_secret_key | base64}}
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
    name: game-library-graylog
    namespace: game-library
data:
    GRAYLOG_PASSWORD_SECRET: {{echo graylog_password_secret | base64}}
    GRAYLOG_ROOT_PASSWORD_SHA2: {{echo graylog_root_password | sha256sum | cut -d " " -f1 | base64}}
    GRAYLOG_MONGODB_URI: {{echo mongodb://user:password@host:27017/graylog?authSource=admin | base64}}
    GRAYLOG_ELASTICSEARCH_HOSTS: {{echo http://user:password@host:9200 | base64}}
type: Opaque
---
# https://kubernetes.github.io/ingress-nginx/examples/auth/basic/
kind: Secret
apiVersion: v1
metadata:
    name: basic-auth
    namespace: game-library
data:
    auth: {{htpasswd -c auth auth-user ; cat auth | base64}}
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
    name: game-library-s3
    namespace: game-library
data:
    S3_ACCESS_KEY_ID: {{echo s3_access_key_id | base64}}
    S3_SECRET_ACCESS_KEY: {{echo s3_secret_access_key | base64}}
    S3_ENDPOINT: {{echo s3_endpoint | base64}}
    S3_CDN_BASE_URL: {{echo s3_cdn_base_url | base64}}
type: Opaque