// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: infoapi.proto

package infoapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CompanyExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyName   string                 `protobuf:"bytes,1,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompanyExistsRequest) Reset() {
	*x = CompanyExistsRequest{}
	mi := &file_infoapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompanyExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyExistsRequest) ProtoMessage() {}

func (x *CompanyExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infoapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyExistsRequest.ProtoReflect.Descriptor instead.
func (*CompanyExistsRequest) Descriptor() ([]byte, []int) {
	return file_infoapi_proto_rawDescGZIP(), []int{0}
}

func (x *CompanyExistsRequest) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

type CompanyExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompanyExistsResponse) Reset() {
	*x = CompanyExistsResponse{}
	mi := &file_infoapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompanyExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyExistsResponse) ProtoMessage() {}

func (x *CompanyExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_infoapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyExistsResponse.ProtoReflect.Descriptor instead.
func (*CompanyExistsResponse) Descriptor() ([]byte, []int) {
	return file_infoapi_proto_rawDescGZIP(), []int{1}
}

func (x *CompanyExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

var File_infoapi_proto protoreflect.FileDescriptor

const file_infoapi_proto_rawDesc = "" +
	"\n" +
	"\rinfoapi.proto\x12\ainfoapi\"9\n" +
	"\x14CompanyExistsRequest\x12!\n" +
	"\fcompany_name\x18\x01 \x01(\tR\vcompanyName\"/\n" +
	"\x15CompanyExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists2`\n" +
	"\x0eInfoApiService\x12N\n" +
	"\rCompanyExists\x12\x1d.infoapi.CompanyExistsRequest\x1a\x1e.infoapi.CompanyExistsResponseB8Z6github.com/OutOfStack/game-library/pkg/infoapi;infoapib\x06proto3"

var (
	file_infoapi_proto_rawDescOnce sync.Once
	file_infoapi_proto_rawDescData []byte
)

func file_infoapi_proto_rawDescGZIP() []byte {
	file_infoapi_proto_rawDescOnce.Do(func() {
		file_infoapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_infoapi_proto_rawDesc), len(file_infoapi_proto_rawDesc)))
	})
	return file_infoapi_proto_rawDescData
}

var file_infoapi_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_infoapi_proto_goTypes = []any{
	(*CompanyExistsRequest)(nil),  // 0: infoapi.CompanyExistsRequest
	(*CompanyExistsResponse)(nil), // 1: infoapi.CompanyExistsResponse
}
var file_infoapi_proto_depIdxs = []int32{
	0, // 0: infoapi.InfoApiService.CompanyExists:input_type -> infoapi.CompanyExistsRequest
	1, // 1: infoapi.InfoApiService.CompanyExists:output_type -> infoapi.CompanyExistsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_infoapi_proto_init() }
func file_infoapi_proto_init() {
	if File_infoapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_infoapi_proto_rawDesc), len(file_infoapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_infoapi_proto_goTypes,
		DependencyIndexes: file_infoapi_proto_depIdxs,
		MessageInfos:      file_infoapi_proto_msgTypes,
	}.Build()
	File_infoapi_proto = out.File
	file_infoapi_proto_goTypes = nil
	file_infoapi_proto_depIdxs = nil
}
