# Options for analysis running.
run:
  # Timeout for analysis, e.g. 30s, 5m.
  # Default: 1m
  timeout: 3m

output:
  formats:
    - format: colored-line-number
      path: stdout

# All available settings of specific linters.
linters-settings:
  govet:
    enable:
      - shadow
  errcheck:
    # List of functions to exclude from checking, where each entry is a single function to exclude.
    # See https://github.com/kisielk/errcheck#excluding-functions for details.
    exclude-functions:
      - (*github.com/gin-gonic/gin.Context).Error
      - (*encoding/json.Decoder).Decode
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - goimports
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - gosimple
    - unused
    - revive
    - typecheck

issues:
  exclude:
    # pprof exposure. closed with auth
    - G108
  exclude-dirs:
    - docs
