services:

  db:
    container_name: games_db
    image: postgres:18-alpine
    ports:
      - "5432:5432"
    restart: on-failure:5
    environment:
      POSTGRES_USER: games-user
      POSTGRES_PASSWORD: games-password
      POSTGRES_DB: games

  redis:
    container_name: redis
    image: redis:8.6-alpine
    command: redis-server #--requirepass
    ports:
      - "6379:6379"
    restart: always

  api:
    container_name: game-library
    image: game-library:latest
    ports:
      - "8000:8000"
      - "6060:6060"
      - "9000:9000"
    environment:
      DB_DSN: postgres://games-user:games-password@db/games?sslmode=disable
      APP_HTTP_ADDRESS: 0.0.0.0:8000
      APP_DEBUG_ADDRESS: 0.0.0.0:6060
      APP_GRPC_ADDRESS: 0.0.0.0:9000
      JAEGER_OTLP_ENDPOINT: host.docker.internal:4318
    depends_on:
      - db
      - redis

  mng:
    container_name: game-library-mng
    image: game-library-mng:latest
    environment:
      DB_DSN: postgres://games-user:games-password@db/games?sslmode=disable
    depends_on:
      - db
