kind: ConfigMap
apiVersion: v1
metadata:
    name: game-library-config
    namespace: game-library
data:
    GIN_MODE: "release"
    APP_ADDRESS: "0.0.0.0:8000"
    DEBUG_ADDRESS: "0.0.0.0:6060"
    APP_ALLOWEDCORSORIGIN: "https://_K8S_URL_"
    AUTH_VERIFYTOKENURL: "https://_K8S_URL_/_auth/token/verify"
    ZIPKIN_REPORTERURL: "http://zipkin-service:9411/api/v2/spans"
    SCHED_FETCH_IGDB_GAMES: "0 5 * * *"
    REDIS_ADDR: "redis-service.game-library.svc.cluster.local:6379"
    REDIS_TTL: "2h"
---
kind: ConfigMap
apiVersion: v1
metadata:
    name: zipkin-config
    namespace: game-library
data:
    ZIPKIN_UI_BASEPATH: "/_trace/zipkin"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: graylog-config
  namespace: game-library
data:
  GRAYLOG_HTTP_EXTERNAL_URI: "graylog-service.game-library.svc.cluster.local:9000"
  GRAYLOG_HTTP_PUBLISH_URI: "https://_K8S_URL_/_log"
  GRAYLOG_ELASTICSEARCH_HOSTS: "_K8S_IP_:9200"
