kind: ConfigMap
apiVersion: v1
metadata:
    name: game-library-config
    namespace: game-library
data:
    GIN_MODE: release
    APP_ADDRESS: 0.0.0.0:8000
    DEBUG_ADDRESS: 0.0.0.0:6060
    APP_ALLOWEDCORSORIGIN: https://_K8S_URL_
    AUTH_VERIFYTOKENURL: https://_K8S_URL_/_auth/token/verify
    ZIPKIN_REPORTERURL: zipkin-service:9411/api/v2/spans
---
kind: ConfigMap
apiVersion: v1
metadata:
    name: zipkin-config
    namespace: game-library
data:
    ZIPKIN_UI_BASEPATH: /_trace/zipkin
