apiVersion: apps/v1
kind: Deployment
metadata:
    name: game-library-deployment
    namespace: game-library
    labels:
        app: game-library
spec:
    replicas: 2
    selector:
        matchLabels:
            app: game-library
    template:
        metadata:
            labels:
                app: game-library
        spec:
            containers:
              - name: game-library
                image: asctod/game-library:latest
                readinessProbe:
                    httpGet:
                        path: /api/readiness
                        port: 8000
                    initialDelaySeconds: 20
                    periodSeconds: 61
                    timeoutSeconds: 5
                    failureThreshold: 3
                livenessProbe:
                    httpGet:
                        path: /api/liveness
                        port: 8000
                    initialDelaySeconds: 20
                    periodSeconds: 59
                    timeoutSeconds: 2
                    failureThreshold: 3
                ports:
                  - name: api
                    containerPort: 8000
                  - name: debug
                    containerPort: 6060
                envFrom:
                  - secretRef:
                      name: game-library-dbconfig
                  - configMapRef:
                      name: game-library-config
                imagePullPolicy: Always
              - name: zipkin
                image: openzipkin/zipkin:2.23
                ports:
                  - name: zipkin
                    containerPort: 9411
            hostAliases:
              - ip: 194.163.162.21
                hostnames:
                  - vmi644117.contaboserver.net
