kind: Secret
apiVersion: v1
metadata:
  name: game-library-dbconfig
  namespace: game-library
data:
  DB_HOST: {{echo db_host | base64}}
  DB_USER: {{echo db_user | base64}}
  DB_PASSWORD: {{echo db_password | base64}}
type: Opaque