kind: Secret
apiVersion: v1
metadata:
  name: game-library-dbconfig
  namespace: game-library
data:
  DB_HOST: {{echo db_host | base64}}
  DB_USER: {{echo db_user | base64}}
  DB_PASSWORD: {{echo db_password | base64}}
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: game-library-igdb
  namespace: game-library
data:
  IGDB_CLIENT_ID: {{echo igdb_client_id | base64}}
  IGDB_CLIENT_SECRET: {{echo igdb_client_secret | base64}}
type: Opaque
---
# https://kubernetes.github.io/ingress-nginx/examples/auth/basic/
kind: Secret
apiVersion: v1
metadata:
  name: basic-auth
  namespace: game-library
data:
  auth: {{ htpasswd -c auth auth-user ; cat auth | base64 }}
type: Opaque
