kind: PersistentVolume
apiVersion: v1
metadata:
  name: graylog-pv
  namespace: game-library
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: graylog-storage-class
  hostPath:
    # make folder writable
    path: /data/graylog
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: graylog-data-pvc
  namespace: game-library
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: graylog-storage-class
