// Code generated by MockGen. DO NOT EDIT.
// Source: internal/taskprocessor/task.go
//
// Generated by this command:
//
//	mockgen -source=internal/taskprocessor/task.go -destination=internal/taskprocessor/mocks/task.go -package=taskprocessor_mock
//

// Package taskprocessor_mock is a generated GoMock package.
package taskprocessor_mock

import (
	bytes "bytes"
	context "context"
	io "io"
	reflect "reflect"
	time "time"

	model "github.com/OutOfStack/game-library/internal/app/game-library-api/model"
	igdbapi "github.com/OutOfStack/game-library/internal/client/igdbapi"
	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
	isgomock struct{}
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockStorage) BeginTx(ctx context.Context) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockStorageMockRecorder) BeginTx(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockStorage)(nil).BeginTx), ctx)
}

// CreateCompany mocks base method.
func (m *MockStorage) CreateCompany(ctx context.Context, c model.Company) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCompany", ctx, c)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCompany indicates an expected call of CreateCompany.
func (mr *MockStorageMockRecorder) CreateCompany(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCompany", reflect.TypeOf((*MockStorage)(nil).CreateCompany), ctx, c)
}

// CreateGame mocks base method.
func (m *MockStorage) CreateGame(ctx context.Context, cg model.CreateGame) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGame", ctx, cg)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGame indicates an expected call of CreateGame.
func (mr *MockStorageMockRecorder) CreateGame(ctx, cg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGame", reflect.TypeOf((*MockStorage)(nil).CreateGame), ctx, cg)
}

// CreateGenre mocks base method.
func (m *MockStorage) CreateGenre(ctx context.Context, g model.Genre) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGenre", ctx, g)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGenre indicates an expected call of CreateGenre.
func (mr *MockStorageMockRecorder) CreateGenre(ctx, g any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGenre", reflect.TypeOf((*MockStorage)(nil).CreateGenre), ctx, g)
}

// GetCompanies mocks base method.
func (m *MockStorage) GetCompanies(ctx context.Context) ([]model.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompanies", ctx)
	ret0, _ := ret[0].([]model.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompanies indicates an expected call of GetCompanies.
func (mr *MockStorageMockRecorder) GetCompanies(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompanies", reflect.TypeOf((*MockStorage)(nil).GetCompanies), ctx)
}

// GetGameIDByIGDBID mocks base method.
func (m *MockStorage) GetGameIDByIGDBID(ctx context.Context, igdbID int64) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGameIDByIGDBID", ctx, igdbID)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGameIDByIGDBID indicates an expected call of GetGameIDByIGDBID.
func (mr *MockStorageMockRecorder) GetGameIDByIGDBID(ctx, igdbID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGameIDByIGDBID", reflect.TypeOf((*MockStorage)(nil).GetGameIDByIGDBID), ctx, igdbID)
}

// GetGenres mocks base method.
func (m *MockStorage) GetGenres(ctx context.Context) ([]model.Genre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGenres", ctx)
	ret0, _ := ret[0].([]model.Genre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGenres indicates an expected call of GetGenres.
func (mr *MockStorageMockRecorder) GetGenres(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGenres", reflect.TypeOf((*MockStorage)(nil).GetGenres), ctx)
}

// GetPlatforms mocks base method.
func (m *MockStorage) GetPlatforms(ctx context.Context) ([]model.Platform, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlatforms", ctx)
	ret0, _ := ret[0].([]model.Platform)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlatforms indicates an expected call of GetPlatforms.
func (mr *MockStorageMockRecorder) GetPlatforms(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlatforms", reflect.TypeOf((*MockStorage)(nil).GetPlatforms), ctx)
}

// GetTask mocks base method.
func (m *MockStorage) GetTask(ctx context.Context, tx pgx.Tx, name string) (model.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTask", ctx, tx, name)
	ret0, _ := ret[0].(model.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTask indicates an expected call of GetTask.
func (mr *MockStorageMockRecorder) GetTask(ctx, tx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTask", reflect.TypeOf((*MockStorage)(nil).GetTask), ctx, tx, name)
}

// UpdateTask mocks base method.
func (m *MockStorage) UpdateTask(ctx context.Context, tx pgx.Tx, task model.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTask", ctx, tx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTask indicates an expected call of UpdateTask.
func (mr *MockStorageMockRecorder) UpdateTask(ctx, tx, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTask", reflect.TypeOf((*MockStorage)(nil).UpdateTask), ctx, tx, task)
}

// MockIGDBAPIClient is a mock of IGDBAPIClient interface.
type MockIGDBAPIClient struct {
	ctrl     *gomock.Controller
	recorder *MockIGDBAPIClientMockRecorder
	isgomock struct{}
}

// MockIGDBAPIClientMockRecorder is the mock recorder for MockIGDBAPIClient.
type MockIGDBAPIClientMockRecorder struct {
	mock *MockIGDBAPIClient
}

// NewMockIGDBAPIClient creates a new mock instance.
func NewMockIGDBAPIClient(ctrl *gomock.Controller) *MockIGDBAPIClient {
	mock := &MockIGDBAPIClient{ctrl: ctrl}
	mock.recorder = &MockIGDBAPIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIGDBAPIClient) EXPECT() *MockIGDBAPIClientMockRecorder {
	return m.recorder
}

// GetImageByURL mocks base method.
func (m *MockIGDBAPIClient) GetImageByURL(ctx context.Context, imageURL, imageType string) (*bytes.Reader, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImageByURL", ctx, imageURL, imageType)
	ret0, _ := ret[0].(*bytes.Reader)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetImageByURL indicates an expected call of GetImageByURL.
func (mr *MockIGDBAPIClientMockRecorder) GetImageByURL(ctx, imageURL, imageType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImageByURL", reflect.TypeOf((*MockIGDBAPIClient)(nil).GetImageByURL), ctx, imageURL, imageType)
}

// GetTopRatedGames mocks base method.
func (m *MockIGDBAPIClient) GetTopRatedGames(ctx context.Context, platformsIDs []int64, releasedAfter time.Time, minRatingsCount, minRating, limit int64) ([]igdbapi.TopRatedGamesResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopRatedGames", ctx, platformsIDs, releasedAfter, minRatingsCount, minRating, limit)
	ret0, _ := ret[0].([]igdbapi.TopRatedGamesResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopRatedGames indicates an expected call of GetTopRatedGames.
func (mr *MockIGDBAPIClientMockRecorder) GetTopRatedGames(ctx, platformsIDs, releasedAfter, minRatingsCount, minRating, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopRatedGames", reflect.TypeOf((*MockIGDBAPIClient)(nil).GetTopRatedGames), ctx, platformsIDs, releasedAfter, minRatingsCount, minRating, limit)
}

// MockUploadcareAPIClient is a mock of UploadcareAPIClient interface.
type MockUploadcareAPIClient struct {
	ctrl     *gomock.Controller
	recorder *MockUploadcareAPIClientMockRecorder
	isgomock struct{}
}

// MockUploadcareAPIClientMockRecorder is the mock recorder for MockUploadcareAPIClient.
type MockUploadcareAPIClientMockRecorder struct {
	mock *MockUploadcareAPIClient
}

// NewMockUploadcareAPIClient creates a new mock instance.
func NewMockUploadcareAPIClient(ctrl *gomock.Controller) *MockUploadcareAPIClient {
	mock := &MockUploadcareAPIClient{ctrl: ctrl}
	mock.recorder = &MockUploadcareAPIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUploadcareAPIClient) EXPECT() *MockUploadcareAPIClientMockRecorder {
	return m.recorder
}

// UploadImage mocks base method.
func (m *MockUploadcareAPIClient) UploadImage(ctx context.Context, data io.ReadSeeker, fileName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadImage", ctx, data, fileName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadImage indicates an expected call of UploadImage.
func (mr *MockUploadcareAPIClientMockRecorder) UploadImage(ctx, data, fileName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadImage", reflect.TypeOf((*MockUploadcareAPIClient)(nil).UploadImage), ctx, data, fileName)
}
