// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v29.3
// source: api/proto/igdb_service.proto

package igdb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CompanyExistsRequest contains the company name to check
type CompanyExistsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CompanyName string `protobuf:"bytes,1,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
}

func (x *CompanyExistsRequest) Reset() {
	*x = CompanyExistsRequest{}
	mi := &file_api_proto_igdb_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompanyExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyExistsRequest) ProtoMessage() {}

func (x *CompanyExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igdb_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyExistsRequest.ProtoReflect.Descriptor instead.
func (*CompanyExistsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_igdb_service_proto_rawDescGZIP(), []int{0}
}

func (x *CompanyExistsRequest) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

// CompanyExistsResponse contains whether the company exists
type CompanyExistsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exists bool `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
}

func (x *CompanyExistsResponse) Reset() {
	*x = CompanyExistsResponse{}
	mi := &file_api_proto_igdb_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompanyExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyExistsResponse) ProtoMessage() {}

func (x *CompanyExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_igdb_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyExistsResponse.ProtoReflect.Descriptor instead.
func (*CompanyExistsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_igdb_service_proto_rawDescGZIP(), []int{1}
}

func (x *CompanyExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

var File_api_proto_igdb_service_proto protoreflect.FileDescriptor

var file_api_proto_igdb_service_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x67, 0x64, 0x62,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04,
	0x69, 0x67, 0x64, 0x62, 0x22, 0x39, 0x0a, 0x14, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x45,
	0x78, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c,
	0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x2f, 0x0a, 0x15, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x69, 0x73,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73,
	0x32, 0x56, 0x0a, 0x0b, 0x49, 0x47, 0x44, 0x42, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x47, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73,
	0x12, 0x1a, 0x2e, 0x69, 0x67, 0x64, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x45,
	0x78, 0x69, 0x73, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x69,
	0x67, 0x64, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x45, 0x78, 0x69, 0x73, 0x74,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2f, 0x5a, 0x2d, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4f, 0x75, 0x74, 0x4f, 0x66, 0x53,
	0x74, 0x61, 0x63, 0x6b, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2d, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72,
	0x79, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x67, 0x64, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_igdb_service_proto_rawDescOnce sync.Once
	file_api_proto_igdb_service_proto_rawDescData = file_api_proto_igdb_service_proto_rawDesc
)

func file_api_proto_igdb_service_proto_rawDescGZIP() []byte {
	file_api_proto_igdb_service_proto_rawDescOnce.Do(func() {
		file_api_proto_igdb_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_igdb_service_proto_rawDescData)
	})
	return file_api_proto_igdb_service_proto_rawDescData
}

var file_api_proto_igdb_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_igdb_service_proto_goTypes = []any{
	(*CompanyExistsRequest)(nil),  // 0: igdb.CompanyExistsRequest
	(*CompanyExistsResponse)(nil), // 1: igdb.CompanyExistsResponse
}
var file_api_proto_igdb_service_proto_depIdxs = []int32{
	0, // 0: igdb.IGDBService.CompanyExists:input_type -> igdb.CompanyExistsRequest
	1, // 1: igdb.IGDBService.CompanyExists:output_type -> igdb.CompanyExistsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_igdb_service_proto_init() }
func file_api_proto_igdb_service_proto_init() {
	if File_api_proto_igdb_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_igdb_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_igdb_service_proto_goTypes,
		DependencyIndexes: file_api_proto_igdb_service_proto_depIdxs,
		MessageInfos:      file_api_proto_igdb_service_proto_msgTypes,
	}.Build()
	File_api_proto_igdb_service_proto = out.File
	file_api_proto_igdb_service_proto_rawDesc = nil
	file_api_proto_igdb_service_proto_goTypes = nil
	file_api_proto_igdb_service_proto_depIdxs = nil
}
