// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v29.3
// source: api/proto/igdb_service.proto

package igdb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IGDBService_CompanyExists_FullMethodName = "/igdb.IGDBService/CompanyExists"
)

// IGDBServiceClient is the client API for IGDBService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IGDBService provides methods for retrieving company information from IGDB
type IGDBServiceClient interface {
	// CompanyExists checks if a company with the given name exists in IGDB (case-insensitive)
	CompanyExists(ctx context.Context, in *CompanyExistsRequest, opts ...grpc.CallOption) (*CompanyExistsResponse, error)
}

type iGDBServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIGDBServiceClient(cc grpc.ClientConnInterface) IGDBServiceClient {
	return &iGDBServiceClient{cc}
}

func (c *iGDBServiceClient) CompanyExists(ctx context.Context, in *CompanyExistsRequest, opts ...grpc.CallOption) (*CompanyExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompanyExistsResponse)
	err := c.cc.Invoke(ctx, IGDBService_CompanyExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IGDBServiceServer is the server API for IGDBService service.
// All implementations must embed UnimplementedIGDBServiceServer
// for forward compatibility.
//
// IGDBService provides methods for retrieving company information from IGDB
type IGDBServiceServer interface {
	// CompanyExists checks if a company with the given name exists in IGDB (case-insensitive)
	CompanyExists(context.Context, *CompanyExistsRequest) (*CompanyExistsResponse, error)
	mustEmbedUnimplementedIGDBServiceServer()
}

// UnimplementedIGDBServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIGDBServiceServer struct{}

func (UnimplementedIGDBServiceServer) CompanyExists(context.Context, *CompanyExistsRequest) (*CompanyExistsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompanyExists not implemented")
}
func (UnimplementedIGDBServiceServer) mustEmbedUnimplementedIGDBServiceServer() {}
func (UnimplementedIGDBServiceServer) testEmbeddedByValue()                     {}

// UnsafeIGDBServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IGDBServiceServer will
// result in compilation errors.
type UnsafeIGDBServiceServer interface {
	mustEmbedUnimplementedIGDBServiceServer()
}

func RegisterIGDBServiceServer(s grpc.ServiceRegistrar, srv IGDBServiceServer) {
	// If the following call panics, it indicates UnimplementedIGDBServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IGDBService_ServiceDesc, srv)
}

func _IGDBService_CompanyExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompanyExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IGDBServiceServer).CompanyExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IGDBService_CompanyExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IGDBServiceServer).CompanyExists(ctx, req.(*CompanyExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IGDBService_ServiceDesc is the grpc.ServiceDesc for IGDBService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IGDBService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "igdb.IGDBService",
	HandlerType: (*IGDBServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CompanyExists",
			Handler:    _IGDBService_CompanyExists_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/igdb_service.proto",
}
