// Code generated by MockGen. DO NOT EDIT.
// Source: internal/api/grpc/infoapi/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/api/grpc/infoapi/service.go -destination=internal/api/grpc/infoapi/mocks/service.go -package=infoapi_mock
//

// Package infoapi_mock is a generated GoMock package.
package infoapi_mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGameFacade is a mock of GameFacade interface.
type MockGameFacade struct {
	ctrl     *gomock.Controller
	recorder *MockGameFacadeMockRecorder
	isgomock struct{}
}

// MockGameFacadeMockRecorder is the mock recorder for MockGameFacade.
type MockGameFacadeMockRecorder struct {
	mock *MockGameFacade
}

// NewMockGameFacade creates a new mock instance.
func NewMockGameFacade(ctrl *gomock.Controller) *MockGameFacade {
	mock := &MockGameFacade{ctrl: ctrl}
	mock.recorder = &MockGameFacadeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGameFacade) EXPECT() *MockGameFacadeMockRecorder {
	return m.recorder
}

// CompanyExistsInIGDB mocks base method.
func (m *MockGameFacade) CompanyExistsInIGDB(ctx context.Context, companyName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompanyExistsInIGDB", ctx, companyName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompanyExistsInIGDB indicates an expected call of CompanyExistsInIGDB.
func (mr *MockGameFacadeMockRecorder) CompanyExistsInIGDB(ctx, companyName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompanyExistsInIGDB", reflect.TypeOf((*MockGameFacade)(nil).CompanyExistsInIGDB), ctx, companyName)
}
