basePath: /api
definitions:
  handler.CreateGameReq:
    properties:
      developer:
        type: string
      genre:
        items:
          type: string
        type: array
      logoUrl:
        type: string
      name:
        type: string
      releaseDate:
        type: string
    required:
    - developer
    - name
    type: object
  handler.CreateRatingReq:
    properties:
      rating:
        maximum: 5
        minimum: 1
        type: integer
    type: object
  handler.GameResp:
    properties:
      developer:
        type: string
      genre:
        items:
          type: string
        type: array
      id:
        type: integer
      logoUrl:
        type: string
      name:
        type: string
      publisher:
        type: string
      rating:
        type: number
      releaseDate:
        type: string
    type: object
  handler.IDResp:
    properties:
      id:
        type: integer
    type: object
  handler.RatingResp:
    properties:
      gameId:
        type: integer
      rating:
        type: integer
      userId:
        type: string
    type: object
  handler.UpdateGameReq:
    properties:
      developer:
        type: string
      genre:
        items:
          type: string
        type: array
      logoUrl:
        type: string
      name:
        type: string
      publisher:
        type: string
      releaseDate:
        type: string
    type: object
  handler.UserRatingsReq:
    properties:
      gameIds:
        items:
          type: integer
        type: array
    type: object
  web.ErrorResponse:
    properties:
      error:
        type: string
      fields:
        items:
          $ref: '#/definitions/web.FieldError'
        type: array
    type: object
  web.FieldError:
    properties:
      error:
        type: string
      field:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: API for game library service
  termsOfService: http://swagger.io/terms/
  title: Game library API
  version: "0.2"
paths:
  /games:
    get:
      description: returns paginated games
      operationId: get-games
      parameters:
      - description: page size
        in: query
        name: pageSize
        type: integer
      - description: last fetched Id
        in: query
        name: lastId
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handler.GameResp'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.ErrorResponse'
      summary: Get games
    post:
      consumes:
      - application/json
      description: creates new game
      operationId: create-game
      parameters:
      - description: create game
        in: body
        name: game
        required: true
        schema:
          $ref: '#/definitions/handler.CreateGameReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handler.IDResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.ErrorResponse'
      summary: Create game
  /games/{id}:
    delete:
      consumes:
      - application/json
      description: deletes game by ID
      operationId: delete-game
      parameters:
      - description: Game ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.ErrorResponse'
      summary: Delete game
    get:
      description: returns game by ID
      operationId: get-game-by-id
      parameters:
      - description: Game ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.GameResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.ErrorResponse'
      summary: Get game
    patch:
      consumes:
      - application/json
      description: updates game by ID
      operationId: update-game
      parameters:
      - description: Game ID
        in: path
        name: id
        required: true
        type: integer
      - description: update game
        in: body
        name: game
        required: true
        schema:
          $ref: '#/definitions/handler.UpdateGameReq'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.ErrorResponse'
      summary: Update game
  /games/{id}/rate:
    post:
      consumes:
      - application/json
      description: rates game
      operationId: rate-game
      parameters:
      - description: game ID
        in: path
        name: id
        required: true
        type: integer
      - description: game rating
        in: body
        name: rating
        required: true
        schema:
          $ref: '#/definitions/handler.CreateRatingReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.RatingResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.ErrorResponse'
      summary: Rate game
  /games/search:
    get:
      description: returns games filtered by provided name
      operationId: search-games
      parameters:
      - description: name to search by
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handler.GameResp'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.ErrorResponse'
      summary: Searches games by name
  /user/ratings:
    post:
      description: returns user ratings for specified games
      operationId: get-user-ratings
      parameters:
      - description: games ids
        in: body
        name: gameIds
        required: true
        schema:
          $ref: '#/definitions/handler.UserRatingsReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: integer
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.ErrorResponse'
      summary: Get user ratings for specified games
schemes:
- http
swagger: "2.0"
