basePath: /api
definitions:
  game.CreateGame:
    properties:
      developer:
        type: string
      genre:
        items:
          type: string
        type: array
      name:
        type: string
      price:
        type: number
      publisher:
        type: string
      releaseDate:
        type: string
    required:
    - developer
    - name
    type: object
  game.CreateGameSale:
    properties:
      discountPercent:
        type: integer
      saleId:
        type: integer
    type: object
  game.CreateRating:
    properties:
      gameId:
        type: integer
      rating:
        type: integer
    type: object
  game.CreateSale:
    properties:
      beginDate:
        type: string
      endDate:
        type: string
      name:
        type: string
    required:
    - beginDate
    - endDate
    type: object
  game.GameInfoResp:
    properties:
      currentPrice:
        type: number
      developer:
        type: string
      genre:
        items:
          type: string
        type: array
      id:
        type: integer
      name:
        type: string
      price:
        type: number
      publisher:
        type: string
      rating:
        type: number
      releaseDate:
        type: string
    type: object
  game.GameResp:
    properties:
      developer:
        type: string
      genre:
        items:
          type: string
        type: array
      id:
        type: integer
      name:
        type: string
      price:
        type: number
      publisher:
        type: string
      releaseDate:
        type: string
    type: object
  game.GameSaleResp:
    properties:
      beginDate:
        type: string
      discountPercent:
        type: integer
      endDate:
        type: string
      gameId:
        type: integer
      sale:
        type: string
      saleId:
        type: integer
    type: object
  game.Rating:
    properties:
      gameId:
        type: integer
      rating:
        type: integer
      userId:
        type: string
    type: object
  game.SaleResp:
    properties:
      beginDate:
        type: string
      endDate:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  game.UpdateGame:
    properties:
      developer:
        type: string
      genre:
        items:
          type: string
        type: array
      name:
        type: string
      price:
        type: number
      publisher:
        type: string
      releaseDate:
        type: string
    type: object
  game.UserRatings:
    properties:
      gameIds:
        items:
          type: integer
        type: array
    type: object
  web.ErrorResponse:
    properties:
      error:
        type: string
      fields:
        items:
          $ref: '#/definitions/web.FieldError'
        type: array
    type: object
  web.FieldError:
    properties:
      error:
        type: string
      field:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: API for game library service
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Game library API
  version: "0.1"
paths:
  /games:
    get:
      description: returns paginated games with extended properties
      operationId: get-all-games-info
      parameters:
      - description: page size
        in: query
        name: pageSize
        type: integer
      - description: last fetched Id
        in: query
        name: lastId
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/game.GameInfoResp'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.ErrorResponse'
      summary: List games info
    post:
      consumes:
      - application/json
      description: creates new game
      operationId: create-game
      parameters:
      - description: create game
        in: body
        name: game
        required: true
        schema:
          $ref: '#/definitions/game.CreateGame'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/game.GameResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.ErrorResponse'
      summary: Create game
  /games/{id}:
    delete:
      consumes:
      - application/json
      description: deletes game by ID
      operationId: delete-game-by-id
      parameters:
      - description: Game ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.ErrorResponse'
      summary: Delete game
    get:
      description: returns game with extended properties by ID
      operationId: get-game-info-by-id
      parameters:
      - description: Game ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/game.GameInfoResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.ErrorResponse'
      summary: Get game info
    patch:
      consumes:
      - application/json
      description: updates game by ID
      operationId: update-game-by-id
      parameters:
      - description: Game ID
        in: path
        name: id
        required: true
        type: integer
      - description: update game
        in: body
        name: game
        required: true
        schema:
          $ref: '#/definitions/game.UpdateGame'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/game.GameResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.ErrorResponse'
      summary: Update game
  /games/{id}/sales:
    get:
      description: returns sales for specified game
      operationId: get-game-sales-by-game-id
      parameters:
      - description: Game ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/game.GameSaleResp'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.ErrorResponse'
      summary: List game sales
    post:
      consumes:
      - application/json
      description: adds game on sale
      operationId: add-game-on-sale
      parameters:
      - description: Game ID
        in: path
        name: id
        required: true
        type: integer
      - description: game sale
        in: body
        name: gamesale
        required: true
        schema:
          $ref: '#/definitions/game.CreateGameSale'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/game.GameSaleResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.ErrorResponse'
      summary: Add game on sale
  /games/rate:
    post:
      consumes:
      - application/json
      description: rates game
      operationId: rate-game
      parameters:
      - description: game rating
        in: body
        name: rating
        required: true
        schema:
          $ref: '#/definitions/game.CreateRating'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/game.Rating'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/web.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.ErrorResponse'
      summary: Rate game
  /games/search:
    get:
      description: returns list of games filtered by provided name
      operationId: search-games-info
      parameters:
      - description: name to search by
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/game.GameInfoResp'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.ErrorResponse'
      summary: Searches games by part of name
  /sales:
    get:
      description: Returns all sales
      operationId: get-sales
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/game.SaleResp'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.ErrorResponse'
      summary: List all sales
    post:
      consumes:
      - application/json
      description: Creates new sale
      operationId: create-sale
      parameters:
      - description: create sale
        in: body
        name: sale
        required: true
        schema:
          $ref: '#/definitions/game.CreateSale'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/game.SaleResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.ErrorResponse'
      summary: Create sale
  /user/ratings:
    post:
      description: returns user ratings for specified games
      operationId: get-user-ratings
      parameters:
      - description: games ids
        in: body
        name: gameIds
        required: true
        schema:
          $ref: '#/definitions/game.UserRatings'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: integer
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.ErrorResponse'
      summary: Get user ratings for specified games
schemes:
- http
swagger: "2.0"
