name: build, push docker image, deploy to k8s cluster

on:
  push:
    branches:
      - "main"
      - "k8s-deploy"

jobs:
  build_push_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up microk8s kubectl tool
        uses: balchua/microk8s-actions@v0.2.2
      #- name: Set up microk8s user
      #  run: |
      #    sudo usermod -a -G microk8s runner
      #    sudo chown -f -R runner ~/.kube
      #    newgrp microk8s
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      #- name: Build and push
      #  id: docker_build
      #  uses: docker/build-push-action@v2
      #  with:
      #    push: true
      #    tags: asctod/game-library:latest,asctod/game-library:${{ github.sha }}

      - name: Show kube configs
        run: |
          sudo microk8s config

      # seems to not work with microk8s 
      #- name: Kubernetes Set Context
      #  uses: Azure/k8s-set-context@v2
      #  with:
      #    method: service-account
      #    bubeconfig: ${{ secrets.K8S_CLUSTER_CONFIG }}

          # TODO: sudo microk8s config > config
          # secret: K8S_CLUSTER_CONFIG
      - name: Kubernetes set context
        run: |
          touch config
          echo "${{ secrets.K8S_CLUSTER_CONFIG }}" > config
          sudo microk8s config > config

      - name: Show kube configs
        run: |
          sudo microk8s config

      - name: Apply configs to Kubernetes cluster
        run: |
          sudo microk8s kubectl apply -f deploy/config.yaml
          sudo microk8s kubectl apply -f deploy/deployment.yaml
